name: Data Transfer Function CI/CD Using Reusable Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  deploy-using-template:
    uses: ./.github/workflows/template-test-build-and-publish-to-azure.yml
    with:
      dotnetVersion: '6.0.x'
      targetPlatform: win-x64
      targetRuntime: net6.0
      projectFolder: Raccoon.Ninja.AzFn.DataTransfer
      projectFile: Raccoon.Ninja.AzFn.DataTransfer.csproj
      releaseFilePrefix: "AzFnDataTransfer"
      publishToAzure: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      azureFunctionAppName: ${{ secrets.AZFN_DATA_TRANSFER_APP_NAME }}
      azurePublishProfile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4FA5B62EE7A54F0FB008C8F7AC985444 }}
