name: Data API Function App CI/CD Workflow Using Template

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/template-test-build-and-publish-to-azure.yml
    with:
      dotnetVersion: '6.0.x'
      targetPlatform: win-x64
      targetRuntime: net6.0
      projectFolder: Raccoon.Ninja.AzFn.DataApi
      projectFile: Raccoon.Ninja.AzFn.DataApi.csproj
      releaseFilePrefix: "AzFnDataApi"
      publishToAzure: true
      azureFunctionAppName: ${{ secrets.AZFN_DATA_API_APP_NAME }}
      azurePublishProfile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_241C3F8D024847BCA5768768B873121E }}
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
