name: CGM Data Display App CI/CD Using Reusable Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write
  deployments: write

jobs:
  deploy-using-template:
    uses: ./.github/workflows/template-test-build-and-publish-to-azure.yml
    with:
      dotnetVersion: '6.0.x'
      targetPlatform: win-x64
      targetRuntime: net6.0-windows
      projectFolder: Raccoon.Ninja.WForm.GlucoseIcon
      projectFile: Raccoon.Ninja.WForm.GlucoseIcon.csproj
      releaseFilePrefix: "CGMDataDisplayApp"
      publishToAzure: false
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
