name: Monthly SonarCloud Analysis

on:
  schedule:
    # Runs at 2 AM UTC on the 1st of every month
    # This will help keep me being on top of any new security issue. :)
    - cron: '0 2 1 * *'

jobs:
  sonarcloud-analysis:
    uses: ./.github/workflows/template-qa-sonarcloud.yml
    with:
      projectKey: 'brenordv_nightscout-companion-apps'
      organization: 'raccoon-ninja'
      branchName: 'master'
      verbose: true
      sonarExclusions: '**/*Usings.cs,Raccoon.Ninja.TestHelpers/*'
      coverageExclusions: '**/*Usings.cs,Raccoon.Ninja.TestHelpers/*,**/*Program.cs,Raccoon.Ninja.WForm.GlucoseIcon/Utils/AppSettings.cs,Raccoon.Ninja.AzFn.DataApi/DataLatestHbA1cFunc.cs,Raccoon.Ninja.AzFn.ScheduledTasks/HbA1cCalcFunc.cs'

    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
