name: SonarCloud analysis on pull requests

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud-analysis:
    uses: ./.github/workflows/template-qa-sonarcloud.yml
    with:
      projectKey: 'brenordv_nightscout-companion-apps'
      organization: 'raccoon-ninja'
      verbose: true
      sonarExclusions: '**/*Usings.cs,Raccoon.Ninja.TestHelpers/*'
      coverageExclusions: '**/*Usings.cs,Raccoon.Ninja.TestHelpers/*,**/*Program.cs,Raccoon.Ninja.WForm.GlucoseIcon/Utils/AppSettings.cs,Raccoon.Ninja.AzFn.DataApi/*Func.cs,Raccoon.Ninja.AzFn.ScheduledTasks/*Func.cs'

    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
      sonarToken: ${{ secrets.SONAR_TOKEN }}
